//17.1 creamos una prueba para llamar el endpoint o al metodo POST
// puedo usar POSTman pero vamos a usar en esta ocacion la extencion RESTclient de VScode
###
POST http://localhost:8083/api/createmovie HTTP/1.1
Content-Type: application/json

{
    "id": 39,
    "adult":false,
    "original_language":"en",
    "original_title":"Blue Beefefeetle",
    "overview":"Un adolescenteeee mexicano encuentra un escarabajo alienígena que le proporciona una armadura superpoderosa.",
    "poster_path":"falta fefefeoto",
    "release_date": "2023-08-09"
}

//21 creamos una prueba para llamar el endpoint o al metodo GET par traer todas las peliculas
###
GET http://localhost:8083/api/movies HTTP/1.1


//22 creamos una prueba para llamar el endpoint o al metodo GET para una sola pelicula apartir del ID
###
GET http://localhost:8083/api/moviebyid/651452d228ad7bebb810203e HTTP/1.1

//23 creamos una prueba para llamar el endpoint o al metodo put
###
PUT http://localhost:8083/api/actualizarmovie/651452d228ad7bebb810203e HTTP/1.1
Content-Type: application/json

{
    "adult":false,
    "original_language":"en",
    "original_title":"kahica cala",
    "overview":"Un vvdvdvddvd proporciona una armadura superpoderosa.",
    "poster_path":"https://i.postimg.cc/CxwDCG0L/Blu-Beetle.jpg",
    "release_date": "2023-08-09"
}

//24 creamos una prueba para llamar el endpoint o al metodo DELETE y eliminar peliculas
###
DELETE  http://localhost:8083/api/deletemovie/651452d228ad7bebb810203e HTTP/1.1
